spring.application.name=spring-profiles-demo

# Default Active Profile
spring.profiles.active=local

# Common JPA Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

debug=truew


# SpEL Example
employee.skills=Java-SpringBoot-PostgreSQL-Docker-Kubernetes

# ConfigurationProperties Example
app.joining-date=2026-05-08
app.office-time=10:30:00
app.deployment-time=2026-05-08T22:15:00

